services:

  tda-db:
    image: postgres:16
    container_name: tda-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - tda_db:/var/lib/postgresql/data

  tda-core:
    build:
      context: tda-core
      dockerfile: Dockerfile
    profiles: [ "fullstack" ]
    container_name: tda-core
    depends_on:
      - tda-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "9000:9000"

  tda-webui:
    build:
      context: tda-webui
      dockerfile: Dockerfile
    profiles: [ "fullstack" ]
    container_name: tda-webui
    depends_on:
      - tda-core
    environment:
      SPRING_PROFILES_ACTIVE: docker
      APP_USERNAME: ${APP_USERNAME}
      APP_PASSWORD: ${APP_PASSWORD}
      APP_ALLOWED_ORIGINS: ${APP_ALLOWED_ORIGINS}
    ports:
      - "9001:9001"

volumes:
  tda_db:
