spring:
  config:
    import: optional:file:.env[.properties]


  application:
    name: tda-core

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml

  web:
    resources:
      add-mappings: false

  security:
    user:
      name: ${APP_USERNAME}
      password: ${APP_PASSWORD}

server:
  port: ${TDA_CORE_PORT}