spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: tda-webui

  web:
    resources:
      add-mappings: false

security:
  app-user:
    name: ${APP_USERNAME}
    password: ${APP_PASSWORD}

server:
  port: 9001

app:
  cors:
    allowed-origin: ${APP_ALLOWED_ORIGINS}
  tda-core:
    api-url: ${APP_CORE_URL}