spring:
  config:
    import: optional:file:.env[.properties]


  application:
    name: tda-webui

  web:
    resources:
      add-mappings: false

  security:
    user:
      name: ${APP_USERNAME}
      password: ${APP_PASSWORD}

server:
  port: 9001

tda_core:
  API_URL: http://tda-core:9000